In [1]:
import pandas as pd

In [2]:
min_definition = pd.read_excel("./../data/interim/min-definition_2020-05-31.xlsx")
max_definition = pd.read_excel("./../data/interim/max-definition_2020-05-31.xlsx")
fully_covered  = pd.read_excel("./../data/interim/fully-covered-definition_2020-05-31.xlsx")

In [3]:
result = pd.concat([min_definition, fully_covered, max_definition], ignore_index=True)
result

    year iso3  stateness  successful_transition                   approach
0   2000  SRB  87.383146                      1  lowest common denominator
1   2003  GEO  45.710637                      1  lowest common denominator
2   2004  UKR  34.936429                      1  lowest common denominator
3   2005  KGZ  11.023552                      0  lowest common denominator
4   2009  MDA  15.703799                      0  lowest common denominator
5   2010  KGZ  15.739882                      0  lowest common denominator
6   2014  UKR  49.303153                      1  lowest common denominator
7   2000  SRB  45.736581                      1              fully covered
8   2003  GEO  21.963296                      1              fully covered
9   2004  UKR  27.762218                      1              fully covered
10  2005  KGZ  13.355782                      0              fully covered
11  2009  MDA  14.586554                      0              fully covered
12  2010  KGZ  14.013135                      0              fully covered
13  2014  UKR  27.528870                      1              fully covered
14  2000  SRB  26.514844                      1             max definition
15  2003  GEO  13.364165                      1             max definition
16  2004  UKR  23.881489                      1             max definition
17  2005  KGZ  12.504533                      0             max definition
18  2009  MDA  14.910096                      0             max definition
19  2010  KGZ  10.761895                      0             max definition
20  2014  UKR  21.448615                      1             max definition

In [4]:
result.to_excel("./../data/processed/stateness.xlsx", index=False)